[package]
name = "story"
version = "0.1.0"
edition = "2021"

[dependencies]
ui.workspace = true
gpui.workspace = true
fake = "2.9.2"
anyhow = "1"
workspace.workspace = true
charts-rs = "0.3"
regex = "1"
chrono = "0.4"
serde = "1"

[lints]
workspace = true
